version: '3'
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - mdb:/data/db
  node:
    depends_on: [mongo]
    restart: always
    build: .
    ports:
      - 4280:4280
volumes:
  mdb:
